# SPDX-License-Identifier: Apache-2.0
# Loom — Reconfigurable Module (RM) synthesis for DFX
#
# Synthesizes loom_emu_top + transformed DUT out-of-context.
# Input:  TRANSFORMED_V — path to transformed.v
#         RM_NAME       — name tag for output (default: "rm")
# Output: work-u250/results/${RM_NAME}_synth.dcp

source $::env(BOARD_DIR)/settings.tcl

set work_dir     $::env(WORK_DIR)
set loom_src     $::env(LOOM_SRC)
set transformed  $::env(TRANSFORMED_V)
set rm_name      [expr {[info exists ::env(RM_NAME)] ? $::env(RM_NAME) : "rm"}]

create_project -in_memory -part $XILINX_PART

# Infrastructure RTL instantiated by loom_emu_top
# (loom_emu_top itself is generated by Loom passes and lives in transformed.v)
read_verilog -sv \
  $loom_src/rtl/loom_axil_demux.sv \
  $loom_src/rtl/loom_emu_ctrl.sv \
  $loom_src/rtl/loom_dpi_regfile.sv \
  $loom_src/rtl/loom_scan_ctrl.sv

# Transformed DUT — contains loom_emu_top + DUT modules
read_verilog $transformed

# OOC synthesis — only loom_emu_top and below
synth_design \
  -top loom_emu_top \
  -flatten_hierarchy rebuilt \
  -mode out_of_context \
  -verilog_define "XILINX=1"

file mkdir $work_dir/results
write_checkpoint -force $work_dir/results/${rm_name}_synth.dcp
report_utilization -file $work_dir/results/${rm_name}_synth_utilization.rpt
