// SPDX-License-Identifier: Apache-2.0
// Loom Simulation Testbench (Standalone)
//
// This testbench is completely DUT-independent. It instantiates:
// - loom_emu_top: the emulation wrapper (generated by emu_top pass)
// - loom_axil_socket_bfm: socket-based AXI-Lite BFM for host communication
//
// The DUT and all emulation infrastructure are contained within loom_emu_top.
// This testbench only provides clock, reset, and the BFM for communication.

`timescale 1ns/1ps

module loom_sim_top;

    // =========================================================================
    // Parameters
    // =========================================================================
    localparam string SOCKET_PATH = "/tmp/loom_sim.sock";
    localparam int    ADDR_WIDTH  = 20;
    localparam int    N_IRQ       = 16;

    // =========================================================================
    // Clock and Reset
    // =========================================================================
    logic clk;
    logic rst_n;

    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;  // 100 MHz
    end

    initial begin
        rst_n = 1'b0;
        #100;
        rst_n = 1'b1;
        $display("[sim] Reset released at t=%0t", $time);
    end

    // =========================================================================
    // AXI-Lite signals between BFM and loom_emu_top
    // =========================================================================
    logic [ADDR_WIDTH-1:0] axil_araddr;
    logic                  axil_arvalid;
    logic                  axil_arready;
    logic [31:0]           axil_rdata;
    logic [1:0]            axil_rresp;
    logic                  axil_rvalid;
    logic                  axil_rready;

    logic [ADDR_WIDTH-1:0] axil_awaddr;
    logic                  axil_awvalid;
    logic                  axil_awready;
    logic [31:0]           axil_wdata;
    logic [3:0]            axil_wstrb;
    logic                  axil_wvalid;
    logic                  axil_wready;
    logic [1:0]            axil_bresp;
    logic                  axil_bvalid;
    logic                  axil_bready;

    logic [N_IRQ-1:0]      irq;

    // =========================================================================
    // Socket BFM
    // =========================================================================
    loom_axil_socket_bfm #(
        .SOCKET_PATH(SOCKET_PATH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .N_IRQ(N_IRQ)
    ) u_bfm (
        .clk_i(clk),
        .rst_ni(rst_n),
        // AXI-Lite Master interface
        .m_axil_araddr_o(axil_araddr),
        .m_axil_arvalid_o(axil_arvalid),
        .m_axil_arready_i(axil_arready),
        .m_axil_rdata_i(axil_rdata),
        .m_axil_rresp_i(axil_rresp),
        .m_axil_rvalid_i(axil_rvalid),
        .m_axil_rready_o(axil_rready),
        .m_axil_awaddr_o(axil_awaddr),
        .m_axil_awvalid_o(axil_awvalid),
        .m_axil_awready_i(axil_awready),
        .m_axil_wdata_o(axil_wdata),
        .m_axil_wstrb_o(axil_wstrb),
        .m_axil_wvalid_o(axil_wvalid),
        .m_axil_wready_i(axil_wready),
        .m_axil_bresp_i(axil_bresp),
        .m_axil_bvalid_i(axil_bvalid),
        .m_axil_bready_o(axil_bready),
        // IRQ inputs
        .irq_i(irq)
    );

    // =========================================================================
    // Loom Emulation Top (generated by emu_top pass)
    // =========================================================================
    // This module contains everything: interconnect, emu_ctrl, dpi_regfile,
    // emu_wrapper, clk_gate, and the DUT itself.
    loom_emu_top u_emu_top (
        .clk_i(clk),
        .rst_ni(rst_n),
        // AXI-Lite Slave interface
        .s_axil_araddr_i(axil_araddr),
        .s_axil_arvalid_i(axil_arvalid),
        .s_axil_arready_o(axil_arready),
        .s_axil_rdata_o(axil_rdata),
        .s_axil_rresp_o(axil_rresp),
        .s_axil_rvalid_o(axil_rvalid),
        .s_axil_rready_i(axil_rready),
        .s_axil_awaddr_i(axil_awaddr),
        .s_axil_awvalid_i(axil_awvalid),
        .s_axil_awready_o(axil_awready),
        .s_axil_wdata_i(axil_wdata),
        .s_axil_wstrb_i(axil_wstrb),
        .s_axil_wvalid_i(axil_wvalid),
        .s_axil_wready_o(axil_wready),
        .s_axil_bresp_o(axil_bresp),
        .s_axil_bvalid_o(axil_bvalid),
        .s_axil_bready_i(axil_bready),
        // IRQ output
        .irq_o(irq)
    );

    // =========================================================================
    // Simulation timeout
    // =========================================================================
    initial begin
        #100_000_000;  // 100ms timeout
        $display("[sim] Timeout!");
        $finish;
    end

endmodule
