#!/bin/sh
set -e

PACKAGE_NAME="xdma"
PACKAGE_VERSION="2020.2.2"

case "$1" in
    remove|purge)
        if [ -x /usr/sbin/dkms ]; then
            dkms remove -m "$PACKAGE_NAME" -v "$PACKAGE_VERSION" --all 2>/dev/null || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
